name: build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]


    steps:
    - uses: actions/checkout@v2
    - name: run makefile
      run: make all
